[master]
35.172.240.19 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-project-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[worker]
3.236.90.164 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-project-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
